# Copyright 2026 3VN Systems
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate the printable files.

    make cad

Writes STL and STEP for every part, for both mechanisms, into
`cad/out/<mechanism>/`. That directory is gitignored: generated
geometry is a build product, and committing it would create a second
copy of the truth that goes stale the moment the profile changes - the
same reason the URDF is expanded at launch instead of being generated
and committed.

STL is what a slicer eats. STEP is what anyone wanting to modify the
part in real CAD needs, and exporting only STL is how an "open" design
becomes un-editable.
"""

import argparse
import pathlib
import sys

from build123d import export_step, export_stl

from threevn_cad import fasteners
from threevn_cad import parts as parts_mod
from threevn_cad import printability
from threevn_cad import profile as prof

OUT = pathlib.Path(__file__).resolve().parents[1] / 'out'


def generate(cfg, mechanism, out_dir):
    """Write every part for one mechanism. Returns a list of summaries."""
    fab = prof.fabrication(cfg)
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for name, builder in sorted(parts_mod.parts_for(mechanism).items()):
        solid = builder(cfg, mechanism=mechanism)
        stl = out_dir / f'{name}.stl'
        step = out_dir / f'{name}.step'
        export_stl(solid, str(stl))
        export_step(solid, str(step))

        box = solid.bounding_box()
        report = printability.report(
            solid, fab['max_overhang_deg'], fab['max_bridge_mm'])
        written.append({
            'orientation': report['best_orientation'],
            'unsupported_mm2': report['unsupported_mm2_best'],
            'part': name,
            'volume_mm3': solid.volume,
            # PLA at 1.24 g/cm3. The printed mass is what the URDF's
            # link masses ought to agree with, and today they are
            # `provenance: estimated` guesses that predate any geometry.
            'mass_g': solid.volume / 1000.0 * 1.24,
            'bbox_mm': (box.size.X, box.size.Y, box.size.Z),
            'stl': stl,
            'step': step,
        })
    return written


#: Parts distal to the shoulder-lift joint: everything that servo has to
#: raise. The turret and base are proximal to it and are not lifted.
LIFTED_PARTS = ('upper_arm_link', 'forearm_link', 'wrist_bracket',
                'gripper_base')

#: Servos distal to the shoulder lift, per mechanism. This is the whole
#: argument for a linkage: the elbow servo moves from the arm to the
#: turret, and 55 g at the end of a lever is worth more than 55 g.
LIFTED_SERVOS = {
    'direct': ('mg996r', 'sg90', 'sg90'),   # elbow, wrist, gripper
    'linkage': ('sg90', 'sg90'),            # wrist, gripper only
}


def compare(cfg, results):
    """
    Report the number the mechanism decision actually turns on.

    Not total printed mass - that favours direct drive and is nearly
    irrelevant. What matters is what the shoulder servo has to lift,
    because that is the joint with the longest lever and the least
    margin.
    """
    servos = {name: spec['mass_kg'] * 1000.0
              for name, spec in cfg['servos'].items()}
    out = {}
    for mechanism, rows in results.items():
        by_part = {row['part']: row['mass_g'] for row in rows}
        # Two fingers and four bushings, not one of each.
        printed = sum(by_part.values())
        printed += by_part.get('gripper_finger', 0.0)
        printed += 3 * by_part.get('pivot_bushing', 0.0)
        lifted = sum(by_part.get(p, 0.0) for p in LIFTED_PARTS)
        lifted += 2 * by_part.get('gripper_finger', 0.0)
        lifted += sum(servos[s] for s in LIFTED_SERVOS[mechanism])
        out[mechanism] = {'printed_g': printed, 'lifted_g': lifted}
    return out


def printing_guide(cfg, mechanism, rows):
    """
    Return a Markdown printing guide for one mechanism.

    GENERATED, beside the parts, for the same reason the parts are
    generated from the profile: a printing guide written by hand goes
    stale the first time a part changes thickness, and it goes stale
    silently because nothing compares the two.
    """
    fab = prof.fabrication(cfg)
    limit, bridge = fab['max_overhang_deg'], fab['max_bridge_mm']

    lines = [
        f'# Printing the {mechanism} arm',
        '',
        'GENERATED by `make cad`. Do not edit - it is rebuilt from the',
        'geometry, so editing it only makes it disagree with the parts.',
        '',
        '## Settings',
        '',
        f'- nozzle **{fab["nozzle_mm"]} mm**, layer '
        f'**{fab["layer_mm"]} mm**',
        f'- walls **{fab["min_wall_mm"]} mm** '
        f'({fab["min_wall_mm"] / fab["nozzle_mm"]:.0f} perimeters)',
        '- PLA. Every mass below assumes 1.24 g/cm3.',
        '- **No support anywhere.** Every part is designed to print',
        f'  unsupported at a {limit:.0f} degree overhang limit, bridging',
        f'  up to {bridge:.0f} mm. If your slicer wants support, check the',
        '  orientation column before enabling it.',
        '',
        '## Parts',
        '',
        '| part | qty | mass | orientation | size |',
        '|---|---|---|---|---|',
    ]

    #: Quantities that are not one. Derived from the assembly, not from
    #: the geometry - a part file says nothing about how many are
    #: needed.
    quantities = {'gripper_finger': 2, 'pivot_bushing': 4}

    total = 0.0
    for row in rows:
        qty = quantities.get(row['part'], 1)
        total += row['mass_g'] * qty
        lines.append(
            '| `{part}` | {qty} | {mass:.1f} g | {orient} | '
            '{x:.0f} x {y:.0f} x {z:.0f} mm |'.format(
                part=row['part'], qty=qty, mass=row['mass_g'] * qty,
                orient=row['orientation'],
                x=row['bbox_mm'][0], y=row['bbox_mm'][1],
                z=row['bbox_mm'][2]))

    lines += [
        '',
        f'**{total:.0f} g of PLA** for one arm.',
        '',
        '## Fasteners',
        '',
        'Counted from the holes in the parts, not from a drawing:',
        '',
        '| hole | count |',
        '|---|---|',
    ]
    for kind, count in sorted(
            fasteners.totals(fasteners.schedule(cfg, mechanism)).items()):
        lines.append(f'| {kind} | {count} |')

    lines += [
        '',
        'These are **cylindrical faces, not a shopping list**, and the',
        'difference matters:',
        '',
        '- A hole through a hollow part appears twice, once per wall.',
        '- Two coaxial holes in two parts are one screw, not two.',
        '- Hole depth is not screw length; that depends on what is behind',
        '  it, which needs an assembly model that does not exist yet.',
        '- Whether a hole takes a nut, a heat-set insert or a',
        '  self-tapping screw has not been decided.',
        '',
        'So: buy an M3 assortment. A confident schedule derived from half',
        'the information would be worse than this note.',
        '',
        '## Before you print',
        '',
        '- **Measure your servo horn.** The horn adapter is built from',
        '  `horn_provenance: estimated` dimensions - horns vary between',
        '  manufacturers even for a servo sold as an MG996R, and these',
        '  are the numbers in the profile most likely to be wrong.',
        '- **Print one bushing and one washer first.** They take minutes',
        '  and they test the press fit and the clearance, which are the',
        '  two things a geometric check cannot verify.',
        '- Nothing here has been printed. These parts pass geometric and',
        '  printability checks, which is a different claim from parts',
        '  that fit together.',
        '',
    ]
    return '\n'.join(lines)


def main(argv=None):
    """Generate parts for both mechanisms and report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--profile', default=None)
    parser.add_argument('--out', default=str(OUT))
    parser.add_argument('--mechanism', choices=parts_mod.MECHANISMS + ('both',),
                        default='both')
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    cfg = prof.load(args.profile)
    wanted = (parts_mod.MECHANISMS if args.mechanism == 'both'
              else (args.mechanism,))

    print()
    collected = {}
    for mechanism in wanted:
        print(f'  {mechanism}')
        results = generate(cfg, mechanism,
                           pathlib.Path(args.out) / mechanism)
        collected[mechanism] = results
        for row in results:
            print('    %-18s %7.0f mm3  %5.1f g  %4.0f x %4.0f x %4.0f mm' % (
                row['part'], row['volume_mm3'], row['mass_g'],
                *row['bbox_mm']))
        print()

    for mechanism, rows in collected.items():
        guide = pathlib.Path(args.out) / mechanism / 'PRINTING.md'
        guide.write_text(printing_guide(cfg, mechanism, rows))

    print(f'  written to {args.out}/<mechanism>/, with PRINTING.md')

    if len(wanted) > 1:
        summary = compare(cfg, collected)
        print()
        print('  mechanism      PLA total   lifted by the shoulder servo')
        for mechanism, row in summary.items():
            print('    %-12s %6.0f g    %6.0f g' % (
                mechanism, row['printed_g'], row['lifted_g']))
        direct = summary['direct']
        linkage = summary['linkage']
        print()
        print('  The linkage needs %.0f g MORE plastic and lifts %.0f g LESS'
              % (linkage['printed_g'] - direct['printed_g'],
                 direct['lifted_g'] - linkage['lifted_g']))
        print('  (%.0f%% less at the joint with the longest lever). Total'
              % (100 * (direct['lifted_g'] - linkage['lifted_g'])
                 / direct['lifted_g']))
        print('  printed mass is the number that favours direct drive and')
        print('  it is nearly irrelevant; this one is not.')
        budget = 250.0
        for mechanism, row in summary.items():
            if row['printed_g'] > budget:
                print()
                print('  NOTE: %s needs %.0f g of PLA against the %.0f g the'
                      % (mechanism, row['printed_g'], budget))
                print('  BOM budgets. docs/bom-hardware.md needs updating or')
                print('  the design needs thinning.')
    print()
    print('  The masses above are what the PARTS weigh. The URDF still')
    print('  carries provenance: estimated guesses that predate any')
    print('  geometry, and reconciling the two is the next honest step -')
    print('  the simulation is currently modelling a robot nobody has')
    print('  designed.')
    print()
    return 0


if __name__ == '__main__':
    sys.exit(main())
